### ISSUE TITLE
Create New Service

### ISSUE THREAD

**Issue by mkuai** [SEI-AMS/pycloud#4] opened 2016-05-20 15:36 UTC
I’m trying to implement a cloudlet-based cyber foraging system using the code. I have a Linux server running PyCloud. The cloudlet is discoverable, which I can verify by running cloudlet-client app from Android device. But when I run speech-android from Android device, it cannot find the related service. I tried two ways of Create New Service (from web-based Cloudlet Manager): 1. Create New VM Image: import a blank VM image, SSH to VM, download and start the speech-server; 2. Select Existing VM Image: import a VM image, which auto-starts the speech-server.  However, neither way worked.  My understanding of the problem is that the service has not been loaded to the cloudlet successfully. But I could not identify the reason. I failed to find further information about creating services from  the website. 

Can you give me some hints about my problem? Also, if possible, can you provide a sample VM that can be used to provide service?

**Comment by sebastian-echeverria** [comment] 2016-05-23 02:10
I'll try to see if I can somehow provide you an exported SVM for you to import, but I would have to figure out how since they are a few GBs in size.

If the Speech App can't find the related service, this is not an issue with the VM itself. The VM may or may not be properly set up. But if the App can't find the service, that means that there is some issue with the metadata of the service, or with the communication between the app and Pycloud. 

Some ideas:
- Are you using the proper service id for speech? I believe the Speech app looks for a service with the service id "edu.cmu.sei.ams.speech_rec_service". If the service you set up on the cloudlet does not have that id, the app won't find it.
- What do you see in the console or log for the Pycloud API? Any errors or warnings?
- Have you looked at the logcat for the app? Usually there are more details about the error it found trying to start a VM for the service in there.

If you can access the console or log for pycloud, or the logcat for the app, but are confused about whatever it says there, you can attach them here and I could take a look.

**Comment by mkuai** [comment] 2016-05-23 06:48
Thank you for the suggestions. I changed the service id to "edu.cmu.sei.ams.speech_rec_service". Now the app can find the service on the cloudlet. But it still has the error when starting Service VM Instance, which is showing on the log of Pycloud API. The error message is "Error starting Service VM Instance: New XML descriptor is bigger than the space available in the saved state file for the original XML descriptor". Any ideas? Thank you!

**Comment by sebastian-echeverria** [comment] 2016-05-23 17:54
Yes, that looks like a known bug that we had fixed at some point. What is the exact branch/commit, or tag, that you are using to test this? Maybe you'll have to update to a newer version, or if that doesn't work or the bug still occurs under certain conditions, I can give you a workaround for it, but I need to know the exact version you are using.

**Comment by mkuai** [comment] 2016-05-23 19:09
I was using the default master branch. Which specific branch/commit/tag should I use?
Thank you!

**Comment by sebastian-echeverria** [comment] 2016-05-23 21:38
That branch is fine, it has some of the fixes but apparently not all of them, some of them are not yet ready to be used. Let me check the workaround and I'll get back to you.

**Comment by sebastian-echeverria** [comment] 2016-05-24 00:39
Short question: what is the name of the VM you set up?

**Comment by mkuai** [comment] 2016-05-24 05:28
I'm using Ubuntu 14.04 to set up VM. 

Meng

**Comment by mkuai** [comment] 2016-05-24 08:10
The name of VM is Ubuntu1404.qcow2 and Ubuntu1404.lqs

**Comment by sebastian-echeverria** [comment] 2016-05-24 12:21
I believe the issue you are seeing is a bug with the way the system handles the internal name of the VM (not the filename). I have that fix on one of the development branches, but since that is not ready for other people to use, I added the fix manually on a new branch, hotfix-vmnamesize. This branch is based on the master branch, only with this fix. I have tested the fix on my branch but not in this new branch, since I don't have a proper environment set up right now for this master branch. Could you try out the hotfix branch and see if the issue is resolved for you?

**Comment by mkuai** [comment] 2016-05-25 02:51
I have tried out the hotfix branch. The previous error doesn't appear. Thanks a lot!
Now I have the new error. It looks like it has some problem when starting VM. I'm not familiar with libvirt. Can you help me identify the problem? Below is the log message of Pycloud API: 

---

Request received: get list of Services. (logged)
Sending response back to 192.168.1.65 (logged)
Request received: get metadata. (logged)
Sending response back to 192.168.1.65 (logged)

---

Request received: start VM with service id edu.cmu.sei.ams.speech_rec_service (logged)
Copying image Ubuntu1404.lqs to new disk image /home/wiman/pycloud/data/temp/instances/203b448a-8f86-4b5d-90fd-cc28a008f270...
Image copied.
Creating qcow2 image /home/wiman/pycloud/data/temp/instances/203b448a-8f86-4b5d-90fd-cc28a008f270/Ubuntu1404.qcow2 based on source image /home/wiman/Ubuntu1404.qcow2...
Formatting '/home/wiman/pycloud/data/temp/instances/203b448a-8f86-4b5d-90fd-cc28a008f270/Ubuntu1404.qcow2', fmt=qcow2 size=8589934592 backing_file='/home/wiman/Ubuntu1404.qcow2' encryption=off cluster_size=4096 lazy_refcounts=off refcount_bits=16

New disk image created.
Bridge enabled:  False
Network Adapter:  enp0s31f6
Original VM Name: ubuntutrusty
New VM Name: VM-203b448a-8f86-4b5d-90fd-cc28a008f270
Setting up port forwarding
Setting up port forwarding from host port 20470 to guest port 10191
Setting up port forwarding from host port 25907 to guest port 22
Resuming from VM image...
libvirt: Domain Config error : operation failed: domain 'ubuntutrusty' already exists with uuid eb2902aa-59ac-4fa3-beb1-aa45c7479929
Error resuming VM: 203b448a-8f86-4b5d-90fd-cc28a008f270 for VM; error is: operation failed: domain 'ubuntutrusty' already exists with uuid eb2902aa-59ac-4fa3-beb1-aa45c7479929
Discarding saved state and attempting to cold boot VM.
Booting up a VM...
libvirt: Domain Config error : operation failed: domain 'ubuntutrusty' already exists with uuid eb2902aa-59ac-4fa3-beb1-aa45c7479929
Removing VM image folder: /home/wiman/pycloud/data/temp/instances/203b448a-8f86-4b5d-90fd-cc28a008f270
Error starting Service VM Instance: operation failed: domain 'ubuntutrusty' already exists with uuid eb2902aa-59ac-4fa3-beb1-aa45c7479929

Thanks a lot!
Meng

**Comment by sebastian-echeverria** [comment] 2016-05-25 03:57
Apparently this is closely related to the previous issue, but you should be able to find a quick workaround this time. So the issue is that our system, every time it creates a new VM from the service template, changes the UUID and name from the template VM into new, random ones, since multiple VMs running at the same time need to have different UUIDs and names. The previous error you saw was because the length of the random name it assigns to a VM it is creating from the template is bigger than the length of the default name you gave to the template, which I see here is "ubuntutrusty". And due to a limitation of libvirt, you can only change a VM name to another name that is of the same length or smaller.

What I did with the hotfix was to NOT change the name of the a new VM created from the template, if the new name doesn't fit (instead of crashing as before). But this means that every new vm you create, from your template, will have the same name. Thus, the error you are now seeing indicates that you have multiple instances already running of VMs. This also means that, currently, you can only have 1 VM running at the same time which was created from the template you used.

I can work on a better fix that is able to create a randomized name anyway even if there is not enough space, by truncating it or something. But meanwhile, you can easily work around this issue by ensuring there are no VMs running based on your template when you try out pycloud. You can find out if there are other VMs running with a command like "ps -aef | grep qemu", or if you are using virt-manager or virsh, through those UIs as well. You can also restart your computer if you want to make sure there are no VMs running (unless you have set up a VM with that name to start up automatically outside pycloud). This should be enough for the system to properly create a new SVM based on your template.

Meanwhile, I'll improve the hotfix to set a random name anyway, but to truncate it so it will fit in whatever space it has. But with the instructions above you shuld be able to try things out, even without the hotfix. If, for some reason I am not seeing right now, the workaround doesn't work, I'll have the new hotfix soon enough anyway.

**Comment by mkuai** [comment] 2016-05-25 15:41
There is no other VM running with the template I used. I checked that with virsh. I’m not sure why it keeps showing “the domain already exists”.

**Comment by sebastian-echeverria** [comment] 2016-05-25 16:49
That is strange. Have you tried restarting the PC? VMs can run on several levels, and you may not see them if you are not specifying that properly on virsh. In any case, I'll try to have the improved hotfix today.

**Comment by mkuai** [comment] 2016-05-25 17:04
I tried restarting the PC and it still has the problem. I did not see any running VMs using "virsh list". I will keep trying.

**Comment by sebastian-echeverria** [comment] 2016-05-25 17:45
Ok, I just pushed the updated hotfix to the same hotfix branch. I am still not sure how you are getting the error you are currently seeing, but now it shouldn't happen since the new names will be new anyway.

**Comment by mkuai** [comment] 2016-05-26 05:51
I tried the updated hotfix. And yes, that issue was solved. But now I'm having another issue when starting the service. Below is the log message:

---

Request received: get list of Services. (logged)
Sending response back to 192.168.1.65 (logged)
Request received: get metadata. (logged)
Sending response back to 192.168.1.65 (logged)

---

Request received: start VM with service id edu.cmu.sei.ams.speech_rec_service (logged)
Copying image Ubuntu1404.lqs to new disk image /home/wiman/pycloud/data/temp/instances/7ce3afe8-f56f-4351-9891-9bb628fc91fa...
Image copied.
Creating qcow2 image /home/wiman/pycloud/data/temp/instances/7ce3afe8-f56f-4351-9891-9bb628fc91fa/Ubuntu1404.qcow2 based on source image /home/wiman/VM/Ubuntu1404.qcow2...
Formatting '/home/wiman/pycloud/data/temp/instances/7ce3afe8-f56f-4351-9891-9bb628fc91fa/Ubuntu1404.qcow2', fmt=qcow2 size=8589934592 backing_file='/home/wiman/VM/Ubuntu1404.qcow2' encryption=off cluster_size=4096 lazy_refcounts=off refcount_bits=16

New disk image created.
Bridge enabled:  False
Network Adapter:  enp0s31f6
Truncating new VM name.
Original VM Name: ubuntutrusty-3
New VM Name: VM-7ce3afe8-f5
Setting up port forwarding
Setting up port forwarding from host port 55417 to guest port 10191
Setting up port forwarding from host port 44223 to guest port 22
Resuming from VM image...
libvirt: QEMU Driver error : internal error: early end of file from monitor: possible problem:
2016-05-26T04:22:46.197146Z qemu-system-x86_64: Features 0x38afffe3 unsupported. Allowed features: 0x79bf8064
2016-05-26T04:22:46.197223Z qemu-system-x86_64: error while loading state for instance 0x0 of device '0000:00:03.0/virtio-net'
2016-05-26T04:22:46.197242Z qemu-system-x86_64: load of migration failed: Operation not permitted
Error resuming VM: 7ce3afe8-f56f-4351-9891-9bb628fc91fa for VM; error is: internal error: early end of file from monitor: possible problem:
2016-05-26T04:22:46.197146Z qemu-system-x86_64: Features 0x38afffe3 unsupported. Allowed features: 0x79bf8064
2016-05-26T04:22:46.197223Z qemu-system-x86_64: error while loading state for instance 0x0 of device '0000:00:03.0/virtio-net'
2016-05-26T04:22:46.197242Z qemu-system-x86_64: load of migration failed: Operation not permitted

Discarding saved state and attempting to cold boot VM.
Booting up a VM...
VM object successfully created, VM started.
SSH available on 192.168.1.93:44223
Checking if service is available inside VM.
Checking if port 55417 is open on IP 192.168.1.93
Successful connection, service is available.
Error starting Service VM Instance: 'NoneType' object has no attribute 'get'

# 

I'm not sure the reason that causes the problem. The OS I'm using is ubuntu 15.10 64-bit.

**Comment by sebastian-echeverria** [comment] 2016-05-26 13:48
So that is a second bug you've found. Just like the bug before this one, the reason we had not seen them before is due to the fact that we always tested with VMs created from within Cloudlet Manager, using a predefined template, but you are using a VM created externally. Which is fine btw, it's just that we had not found these bugs before because of that. So thanks for helping us improve the system!

This bug should be fixed now in the same hotfix branch as before. The system was assuming there would always be a VNC configuration set up for the VM, which is true for VMs created with Cloudlet Manager, but it seems not to be true for the VM you created. The system should be handling that case properly now. Please do test and let me know if you find any other issues.

Btw, we've always tested the system with Ubuntu 14.04, but so far, from your logs, I've seen no indication of issues due to your use of a newer version.

**Comment by mkuai** [comment] 2016-05-27 07:26
I have tried the updated version of the hotfix branch. Now the cloudlet server can start the service successfully when running Android Speech client! But when I click "SEND TO SERVER" (it has sound file in the folder), it has the error:

...
Finished sending Record_0001.wav
Getting response from server...
An IOException has occured: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
No response or error from server...

I'm thinking maybe it's because the speech-server in VM is not running properly. I just made the server program running automatically when VM starts. Is that correct?

**Comment by sebastian-echeverria** [comment] 2016-05-27 12:27
If the VM is starting, it means that at least everything that pycloud did worked well. After that, communication ocurrs directly between the app and its server, without any intervention from pycloud. So your theory that speech server is not running properly makes sense.

What you did is correct. What I would recommend to figure out what is going on is the following: start the VM through Speech as you just did, but then, before Sending to Server, ssh into the VM that is running the speech server. There are a couple of options here:
- Sometimes speech server may take a while to start running, so you may want to wait and try the Send button again in a minute or so. 
- If you are using the default Upstart .conf file that comes with Speech Server, the "console log" command there logs the output of Speech Server into the folder /var/log/upstart/ . You could then try the Send button on the app, and check what is going on with that log.
- You could stop the Upstart job, and run speech in your ssh console. Then try the Send to Server button again, and see what the server writes to the console.

Let me know if any of these work for you, or what you are seeing on the logs. Most likely it is just a case of speech server taking to long to start accepting connections.

**Comment by sebastian-echeverria** [comment] 2016-05-27 12:43
Btw, note also this line from the console: "Setting up port forwarding from host port 55417 to guest port 10191". In that case, this means that port 55417 is the port that Speech App is going to use when connecting to the cloudlet and sending requests, and port 10191 is the port that Speech Server is going to be listening on inside the VM. The first port, 55417, is dynamic, and it is changed each time a new VM is created. But the second port, 10191, is not, and it is part of the Service metadata. I assume you set the port to be 10191 when you created the Service in Cloudlet Manager. But note that by default, if you use the run.sh script in the src/dist folder of Speech Server, the server is actually listening on port 9001. Regardless of what you actually did, make sure that the port Speech Server is listening on inside the VM is the same port you configure in the Service metadata in Cloudlet Manager. Otherwise Speech App won't be able to get its requests properly forwarded to the appropriate internal port.

**Comment by mkuai** [comment] 2016-06-02 07:58
I guess I didn't make the auto-start work properly. Now I just SSH to the VM and start the server manually. It looks like the client and the server are connected but some configuration file of sever is missing. Here is the log:

wiman@ubuntu1404-vm:~/speech-server$ gradle run
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Using default server port 10191
SpeechRecognitionServer V5.0 listening on 10191 ...
Jun 02, 2016 2:00:24 AM edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler channelConnected
INFO: Client channel connected ... 
Jun 02, 2016 2:00:24 AM edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler messageReceived
INFO: Client message received ... 
Jun 02, 2016 2:00:24 AM edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler messageReceived
INFO: Created a temp audio file of size 302124 at /tmp/audio2043091299856358709.wav in 1 ms.
Jun 02, 2016 2:00:24 AM edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler getSpeechOutput
INFO: audio url:file:/tmp/audio2043091299856358709.wav
Jun 02, 2016 2:00:24 AM edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler getSpeechOutput
INFO: config url: file:./config/config.xml
java.lang.RuntimeException: java.io.FileNotFoundException: ./config/config.xml (No such file or directory)
    at edu.cmu.sphinx.util.props.ConfigurationManager.<init>(ConfigurationManager.java:60)
    at edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler.getSpeechOutput(SpeechRecognitionServerHandler.java:158)
    at edu.cmu.sei.ams.clouldet.speechrec.server.SpeechRecognitionServerHandler.messageReceived(SpeechRecognitionServerHandler.java:118)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:321)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:214)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:351)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:282)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:202)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: ./config/config.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at java.net.URL.openStream(URL.java:1048)
    at edu.cmu.sphinx.util.props.SaxLoader.load(SaxLoader.java:74)
    at edu.cmu.sphinx.util.props.ConfigurationManager.<init>(ConfigurationManager.java:58)
    ... 14 more

**Comment by sebastian-echeverria** [comment] 2016-06-02 12:08
I would recommend you use the src/dist folder inside the repo, all the needed config is in there. Copy that whole folder over to the VM. It contains the ./config folder with the required configuration, plus some other files needed to work properly (such as a ./models and another folder with a model). It also has a usage.txt readme, and a speech_rec_server.conf that you may modify and use to start it as an Upstart job properly.

So, I would recommend you to:
- Compile speech server to create a distribution
- Move the src/dist folder to the VM
- Move the compiled speech server into that folder in the VM, if it didn't get put automatically in the dist folder
- Run the server from there
- (If that works, modify and try the speec_rec_server.conf file to set it up to properly auto start)

**Comment by mkuai** [comment] 2016-06-03 05:03
I think previously I didn't run the server properly. Now I'm running /bin/speech-server and it is working well. Now the client can get the response from the server. Thank you very much!

**Comment by sebastian-echeverria** [comment] 2016-06-03 12:33
Great! Good to hear that. Thanks for helping us find some hidden bugs!

**Closed as completed by sebastian-echeverria** 2016-06-03 12:33 UTC
Labels: bug
