### ISSUE TITLE
Does this project contain Dynamic VM Synthesis technology?

### ISSUE THREAD

**Issue by t00197857** [SEI-AMS/pycloud#6] opened 2016-11-18 01:40 UTC
Hello。I studied the code of pycloud under https://github.com/SEI-AMS/pycloud. But I found that the Dynamic VM Synthesis approach is NOT implemented in this project. And I cannot find any descriptions about baseVM and launchVM in the project wiki pages. It seems that the code doesn’t match the process described in the two papers, Transient Customization of Mobile Computing Infrastructure-mobivirt2008 and The Case for VM-based Cloudlets in Mobile Computing. Am I right? I’m not so sure about this.

**Comment by GALewis** [comment] 2016-11-18 02:09
That is correct. Our project does not use Dynamic VM Synthesis because it is not optimal for network-constrained environments which is the target of this work. VMs are pre-provisioned on the cloudlet, which also hosts the client to use the VM in case the mobile device does not have it (similar to an app store)

**Comment by sebastian-echeverria** [comment] 2016-11-18 02:48
The code in this repository is not the code of our first prototypes. The first prototypes we developed did include VM Synthesis, and the references you mention may be talking about that version of the code. That implementation, however, was never open-sourced. The code included in this repo is of a newer version of the system that no longer contains VM Synthesis, for the reasons GALewis described above.

**Comment by matthewparkhw** [comment] 2016-11-18 09:02
OK. Thank you for your reply. 

Then, my next question is, which paper describes the architecture and technologies used in this project? And what's the relationship between this project and https://github.com/cmusatyalab/elijah-cloudlet. 

What I'm doing now is to reproduce cloudlet demo (either one is ok) on our own testbed and explain the architecture and technologies (the more the better) that are used in it. So I need match the code and its corresponding papers. Would you please give me some suggestions about which project to use and which paper to study. Thank you.

**Comment by matthewparkhw** [comment] 2016-11-18 09:20
BTW, I cannot find any code on VM manipulation. If I want to study the code about the techniques, such as dynamic VM synthesis, baseVM creation, Overlay creation, Cloudlet-Ready Client App generation, Just-in-Time Provisioning, then which project should I go?

**Comment by matthewparkhw** [comment] 2016-11-18 09:23
BTW, I cannot find any code on VM manipulation techniques in pycloud project. The project is more like a mechanism that implement the process of cyber foraging, rather then the techniques described in the relevant papers.

If I want to study the code about the techniques, such as dynamic VM synthesis, baseVM creation, Overlay creation, Cloudlet-Ready Client App generation, Just-in-Time Provisioning, then which project should I go?

**Comment by matthewparkhw** [comment] 2016-11-18 09:27
BTW, I cannot find any code on VM manipulation techniques in pycloud project. The project is more like a mechanism that implement the process of cyber foraging, rather than the techniques described in the relevant papers.

If I want to study the code about the techniques, such as dynamic VM synthesis, baseVM creation, Overlay creation, Cloudlet-Ready Client App generation, Just-in-Time Provisioning, etc., then which project should I go?

**Comment by sebastian-echeverria** [comment] 2016-11-18 12:08
Again, the code we have here is not the platform we developed for VM manipulation. This code is of a different project we created based on that one, this time focused on survivability. The first paper that refers to the code in this repo is "Cyber-Foraging for Improving Survivability of Mobile Systems" (http://ieeexplore.ieee.org/abstract/document/7357644/). The current version of the code in this repo, which has more security features, is referenced in the paper "Establishing Trusted Identities in Disconnected Environments", which was just presented and I think is not available online yet.

The code described in the papers "Cloudlet-Based Cyber-Foraging for Mobile Systems in Resource-Constrained Edge Environments", “Tactical Cloudlets: Moving Cloud Computing to the Edge” and “On-Demand VM Provisioning for Cloudlet-Based Cyber-Foraging in Resource-Constrained Environments”, is the previous platform we developed, which did have several VM manipulation techniques: VM Synthesis, On-Demand VM Provisioning, Application Virtualization, and others.  Unfortunately, this code has not been open-sourced, so I can't point you to a link where you can review this code. The code you see in this repo is based on that one, but with all the VM manipulation stuff removed from it.

Finally, the Elijah project is a sort of brother project to the first platform we developed (the one with VM Synthesis, for which the code is not available). In that first platform we developed, we explored some of the same concepts that were being explored in the Elijah project, such as VM Synthesis. Both projects started with VM Synthesis at their cores, but from there diverged substantially. The Elijah project focused on optimizing VM Synthesis and exploring other issues, while we mostly started testing alternatives to VM Synthesis and comparing those to it.

So, in terms of papers and code:
- The code referenced in the papers  "Cloudlet-Based Cyber-Foraging for Mobile Systems in Resource-Constrained Edge Environments", “Tactical Cloudlets: Moving Cloud Computing to the Edge” and “On-Demand VM Provisioning for Cloudlet-Based Cyber-Foraging in Resource-Constrained Environments” is not available anywhere as of now.
- The code referenced in "Cyber-Foraging for Improving Survivability of Mobile Systems" is the code available in tag 0.1.0 of this repo.
- The code referenced in the (I think not yet available online) paper "Establishing Trusted Identities in Disconnected Environments"  is the code available in tag 0.4.1 of this repo.

**Comment by sebastian-echeverria** [comment] 2016-11-18 12:11
And the paper "The Case for VM-based Cloudlets in Mobile Computing" references some code in the Elijah project repo, but I have no idea what version exactly. I guess the "Transient Customization of Mobile Computing Infrastructure" paper refers to code that may be in the elijah repo as well, but I am not sure where they actually put it.

**Comment by Lincarl7236** [comment] 2016-11-22 12:45
Hello!Would you please give me some suggestions which repo should clone from the GitHub?   
"Clone the repo from GitHub into a folder"

**Comment by sebastian-echeverria** [comment] 2016-11-22 14:12
It refers to this repo, https://github.com/SEI-AMS/pycloud . Depending on what you want exactly, you may want to clone the latest version of the master branch of the repo, or you may want to download a tag. In the messages above there is a description of what each significantly different tag has.

**Comment by Lincarl7236** [comment] 2016-11-24 02:13
OK.Thank you for your reply.

**Comment by Lincarl7236** [comment] 2016-11-24 12:01
Execute the following commands:sudo bash start_dev_manager.sh 
There is a question  "The 'adb==1.1.1' distribution was not found and is required by pycloud" . What should we do  to solve this problem.

**Comment by sebastian-echeverria** [comment] 2016-11-24 12:13
It sounds as if you did not set up the computer properly. Did you run the full_dev_setup.sh script as indicated in the instructions, and was it able to install all required packages? adb 1.1.1 is a Python package that is installed by the full_dev_setup.sh script.

If you ran the full_dev_setup.sh script as sudo, eg, "sudo bash full_dev_setup.sh", you may want to try again without sudo, eg, "bash full_dev_setup.sh". There may be some permission issues which may have lead to the packages not installing or not installing in the proper locations.

**Comment by Lincarl7236** [comment] 2016-11-24 13:48
Based on your suggestions, I found that I did not set up the computer properly. There may be some permission issues lead to the question.When I ran the bash  full_dev_setup.sh script .there are some questions，eg， "1. The directory '/home/lin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. 2   Failed building wheel for netifaces.  3. Adduser: "kvm" group does not exist ,and so on.  How can we solve these questions?

**Comment by sebastian-echeverria** [comment] 2016-11-24 15:21
Btw, point 1 you mention there is only a warning, bu the rest look like errors. Let me check and I'll get back to you. What is the version of the host operating system you are installing this on? And what branch are you using, the latest version on master?

**Comment by Lincarl7236** [comment] 2016-11-25 12:14
The system I used is Ubuntu version 14.10. And  I follow the instructions in the "Development Environment Setup"  to test running the pycloud server.
Firstly,I clone the repo from GitHub,"https://github.com/SEI-AMS/pycloud". The  path below is relative to the  ./scripts folder .Secondly,  I  execute the command" bash full_dev_setup.sh". Then I log out from my Linux user, and log back in ，and to create the ./data folder. Finally ,I execute the commands from the root repo folder "sudo bash start_dev_manager.sh"  and  "sudo bash start_dev_api.sh". Is it right?

**Comment by sebastian-echeverria** [comment] 2016-11-25 12:55
Yes, that is correct. Yesterday I tested those same instructions on a clean Ubuntu 14.04 machine, and other than having to create the data folder, I had no issues. I guess it is possible that Ubuntu 14.10 may have some differences that could create issues, but it is not what I would expect. 

If you just followed that instructions again and you are still having issues, please reply back with an attached file that indicates the console output of the "bash full_dev_setup.sh" command, and of the "sudo bash start_dev_manager.sh" commands, and I will take a closer look at those logs.

**Comment by Lincarl7236** [comment] 2016-11-26 08:28
What is the location of the data dolder? Today I test those instructions on a Ubuntu 14.04 machine,I do not find the data folder.So,I creat the data folder from the root repo folder, and I get a result ,eg,"Starting server in PID 2980.serving on http://127.0.0.1:9998" and"Starting server in PID 3149.serving on 0.0.0.0:9999 view at http://127.0.0.1:9999" .Is it right?

**Comment by sebastian-echeverria** [comment] 2016-11-26 17:17
Yes, that means it is working properly! I guess there is some
incompatibility with 14.10 then.

**Comment by Lincarl7236** [comment] 2016-11-28 15:51
OK, thank you for your help.

**Comment by Lincarl7236** [comment] 2016-11-29 13:39
Hello!
KD-Cloudlet comprises a total of 7 GitHub projects: pycloud, cloudlet-client, client-lib-android, client-lib ,
android-logger, speech-server and speech-android. We can use the repo of pycloud to  test running the pycloud server. But we do not know that what can we do with other repos. We want to set up  a production cloudlet, and  we have some questions, eg, "1. Is it necessary "Development Environment Setup" . 2. Where should we execute those commands in  Production Setup. 3. Can we use pycloud in the case of a successful test？"

**Comment by sebastian-echeverria** [comment] 2016-11-29 14:36
1.  You can either follow the Development Setup or the Production Setup. You don't really need to do both. The Production Setup is in case you want a "cleaner" installation for production purposes. If you just want to test, following the instructions in the Development Environment Setup is enough.
2. As I mentioned above, if the Development Env. Setup is working for you and you are just testing, you can ignore the Production Setup steps.
3. If you were able to properly start Pycloude Cloudlet Manager and Pycloud API (and from what I saw on your previous message, you were), then yes, you can use your setup to use pycloud. Regarding the other proyects:
- Some of them are libraries that you can just ignore: client-lib-android, client-lib, and android-logger are dependencies of some other projects, so unless you want to look at the code, you don't have to worry about those, they are automatically included when compiling other projects.
- cloudlet-client is a helper Android App that can help check if your cloudlet is properly set up and also help installing other apps on your phone, but it is not needed either for Pycloud to function.
 - speech-server and speech-android are a server and client programs that can be used to test Pycloud. In summary, you have to install speech-android on a phone one one side; and on the other side, use Pycloud Cloudlet Manager to create a VM with speech-server on it. Then you can use the app to start the VM with the server inside it, and test it out.  There is more information on how to do this in the wiki page https://github.com/SEI-AMS/pycloud/wiki/Service-VMs, section Service Management/Service VM Creation.

**Comment by Lincarl7236** [comment] 2016-12-01 13:37
Thank you for your reply .  I could not find the directory containing the deb package to execute the command "sudo dpkg --force-overwrite -i python-pycloud_0.2.0_all.deb" and I could not find the version number. Maybe my question is stupid, I am a novice, is very interested in this. I am sorry for the trouble I have caused you.

**Comment by sebastian-echeverria** [comment] 2016-12-01 13:46
As I above, if you already set up the dev environment, you do NOT need to follow the instructions in the "2. Production Setup" section. Ignore that whole section, and its subsections, including the "Installation", "Post-Installation Files and Folders", and "Starting Pycloud". Those are only needed if you were setting up a long-term server. Just jump to section "3. Using Pycloud", and then follow the Service VM instructions I added above.

**Comment by Lincarl7236** [comment] 2016-12-02 15:57
Thank you for your reply. When I create New Service VM, there is a question, eg, “There was a problem starting and connecting to service vm: Error creating Service VM: global name 'g' is not defined” . And I have no idea  about how to generate the Disk Image file (.qcow2) and VM State Image file (.lqs). The Ubutntu 14.04 I used based on VMware Workstation.

**Comment by sebastian-echeverria** [comment] 2016-12-06 02:52
Yes, there was a bug you just found which we had fixed in the working branch, but it was not fixed on the master branch. I just fixed it, so please pull from the repo to get this update. This should fix the "g not defined" error.

Regarding the creation of the files, the system will create them for you. The system will create the lqs file, so you don't have to worry about that one. You do have to supply a base disk image file, in form of a raw or qcow2 disk image, for the system to create the VM. In Ubuntu, you can create a new VM (and thus a new disk image which you can later use here) through virt-manager, for example. If you already have a VMWare disk image, you can convert it to qcow2 using qemu-img (google for that tool and that conversion and you should find examples of how to do it; the conversion is pretty simple with that tool).

**Comment by Lincarl7236** [comment] 2016-12-10 03:39
I cloned the  new repo and that problem has been solved . But when I create New Service VM, there is a question, eg,"There was a problem starting and connecting to service vm: Error creating Service VM: internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/home/lin/pycloud-master1/data/temp/servicevm/49345234-6fc5-4331-b1a2-84e4abc70187/lin100.qcow2,if=none,id=drive-ide0-0-0,format=qcow2: could not open disk image /home/lin/pycloud-master1/data/temp/servicevm/49345234-6fc5-4331-b1a2-84e4abc70187/lin100.qcow2: Could not open '/home/lin/pycloud-master1/data/temp/servicevm/49345234-6fc5-4331-b1a2-84e4abc70187/lin100.qcow2': Permission denied".

**Comment by sebastian-echeverria** [comment] 2016-12-12 01:53
I can think of only two cases where that may happen: if the source disk image file you have has only read permissions, or if you are running cloudlet manager not as sudo. Are you sure you are starting cloudlet manager as "sudo bash start_dev_manager.sh"? And is your disk image file read-only?

**Comment by Lincarl7236** [comment] 2016-12-19 06:35
No,my disk image file is not read-only. All users have read and write permissions.

**Comment by sebastian-echeverria** [comment] 2016-12-19 11:20
Assuming you are running cloudlet manager as sudo, check the file
/etc/libvirt/qemu.conf. Check the user and group settings there. If they
are set to a user, try either commentting them out, or setting both to
root. Also comment out dynamic_ownership if needed. Then stop and start the
libvirt daemon (audio stop libvirt-bin, audio start libvirt-bin).

On Dec 19, 2016 03:35, "Lincarl7236" <notifications@github.com> wrote:

No,my disk image file is not read-only. All users have read and write
permissions.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SEI-AMS/pycloud/issues/6#issuecomment-267892167>, or mute
the thread

**Comment by sebastian-echeverria** [comment] 2016-12-22 15:29
Btw, that should have been "(sudo stop libvirt-bin, sudo start libvirt-bin)".... "audio" was the autocorrector....

**Comment by sebastian-echeverria** [comment] 2016-12-24 00:27
And btw, the issue you were seeing with the permissions was due to the setup script being out of date. It was setting the user and group in /etc/libvirt/qemu.conf to the current user, instead of "root". If you set both values to "root" (with quotes), and set dynamic_ownership to 1 just in case, and then stop and start the daemon, the permission issue should go away.

**Comment by Lincarl7236** [comment] 2017-01-11 08:28
Thank you for your reply. I will try again.

**Comment by mejing** [comment] 2017-04-17 13:50
hello!
I plan to use Pycloud Cloudlet Manager to create a VM with speech-server on it. but when  I create a new VM,I don't know which required files I shuld Transfer for the server to the VM.

**Comment by sebastian-echeverria** [comment] 2017-04-17 23:52
Hello mejing, the page [Service-VMs](https://github.com/SEI-AMS/pycloud/wiki/Service-VMs) in this wiki has information about creating SVMs, and the Speech page  [here](https://github.com/SEI-AMS/speech-server) gives more information about how to create that particular SVM fo Speech. More specifically, it indicates that  "The ./src/dist folder has all configuration and model files that need to be on the same folder as the speech-server executable for it to run properly."

However, I know it can still be a bit painful to set the SVM up manually. I can suggest you the following to create the SVM more easily: there is a script to automatically create an osV-based Speech SVM in the Speech Server repository. The "capstan_setup.sh" script will install capstan for you, which is  a tool for creating osV-based SVMs. Once you have that setup, the "create_svm_disk_image.sh" script will create a packaged Speech SVM that you can import in Cloudlet Manager with the Import button/feature.

Try that; if it doesn't work out for some reason, I can try helping you out or eventually sharing a link to the resulting packaged SVM as well.

**Comment by mejing** [comment] 2017-04-18 07:01
thank you for your reply!
as your said,I tried that.but when I create a packaged Speech SVM,there are some errors as follows:
create_svm_disk_image.sh: 行 6: capstan: 未找到命令
cp: 无法获取"/home/jing/.capstan/repository/speech_osv/speech_osv.qemu" 的文件状态(stat): 没有那个文件或目录

 Does it mean that I did not finish capstan installed or some problem I didn't realized.

**Comment by mejing** [comment] 2017-04-18 07:32
thank you for your reply!
as your said,I tried that.but when I create a packaged Speech SVM,there are some errors as follows:
create_svm_disk_image.sh: 行 6: capstan: No command found
Cp: ​​can not get "/home/jing/.capstan/repository/speech_osv/speech_osv.qemu" file status (stat): no that file or directory

Does it mean that I did not finish capstan installed or some problem I didn't realized.

**Comment by mejing** [comment] 2017-04-18 07:49
thank you for your reply!
as your said,I tried that.but when I create a packaged Speech SVM,there are some errors as follows:
create_svm_disk_image.sh: line 6: capstan: No command found
Cp: ​​can not get "/home/jing/.capstan/repository/speech_osv/speech_osv.qemu" file status (stat): no that file or directory

Does it mean that I did not finish capstan installed or some problem I didn't realized.

**Comment by sebastian-echeverria** [comment] 2017-04-18 11:12
Yes, that sounds as if Capstan did not install properly. Maybe it depends on the OS and distribution you are running under? Check the capstan_setup.sh file, try running each command independently, to figure out where the issue is. Or check the Capstan page for alternate Capstan setup steps. I'll check if I can generate the SVM locally meanwhile, to share it with you if you are unable to install Capstan.

**Comment by mejing** [comment] 2017-04-19 08:42
I  checked the capstan_setup.sh file,and runned each command independently,and didn't report any errors.but when I runned create_svm_disk_image.sh ,it still reported: line 6: capstan: No command found.and I can find Capstan application in /home/jing/bin/.but I didn't know if ~/.capstan/repository is there when it was installed.
besides I checked the Capstan page,and try to install Capstan follow [https://github.com/cloudius-systems/capstan/wiki/Capstan-Installation](url),and then when I runned create_svm_disk_image.sh ,it still reported: line 6: capstan: No command found.

**Comment by sebastian-echeverria** [comment] 2017-04-19 13:35
The issue is before the line with ~/.capstan/repository.... is in the line that states "capstan build ...", from what I see. Ignore the script for a second. Can you simply execute the "capstan" command on its own? Does that fail? ~/.capstan/repository is where capstan will store VMs after downloading/creating them.

**Comment by mejing** [comment] 2017-04-20 01:07
yes,I simply execute the "capstan" command on its own.but it report：open Capstanfile: no such file or directory.

**Comment by sebastian-echeverria** [comment] 2017-04-20 02:34
Well, that mean it is installed... if you run "capstan build <name>" from a folder, it should execute the script called Capstanfile in that folder, and create a VM named <name>. Try executing that command from the folder itself. In any case, here is a temporary link to what would be the result of the script (a packaged SVM that can be imported in Cloudlet Manager). Please let me know when you have downloaded it so I can remove it: https://www.dropbox.com/s/g7nqizfjq21vb3x/edu.cmu.sei.ams.speech_rec_service_osv.csvm?dl=1 .

**Comment by mejing** [comment] 2017-04-20 13:56
yes,I have downloaded it.and when I imported it in Cloudlet Manager,the terminal reported asfollows,
Starting server in PID 2748.
serving on http://127.0.0.1:9998
Starting SVM import
Starting SVM import
Importing file:  /home/jing/edu.cmu.sei.ams.speech_rec_service_osv.csvm
Exception while importing:  "filename u'edu.cmu.sei.ams.speech_rec_service.qcow2.lqs' not found"

**Comment by sebastian-echeverria** [comment] 2017-04-20 14:37
What version of pycloud/cloudlet manager are you using? Versions previous to 3.0.0, which is the same that is currently in the master branch, do not show that error messages. Older versions do require a lqs file that is not included in the packaged SVM you downloaded.

**Comment by Lincarl7236** [comment] 2017-07-10 00:45
Hello!
Can you give me some relevant papers? I  want to know the design principles of KD-Cloudlet.

**Comment by sebastian-echeverria** [comment] 2017-07-10 13:34
Hello, here are some relevant papers we've written along with the evolution of the platform. Do note that some of the earlier features (like On-Demand VM Provisioning) have been removed from the current platform, or are part of earlier versions of the platform which were not hosted in GitHub.

- [Cloudlet-based cyber-foraging for mobile systems in resource-constrained edge environments](http://dl.acm.org/citation.cfm?id=2591119)
- [Tactical Cloudlets: Moving Cloud Computing to the Edge](http://ieeexplore.ieee.org/abstract/document/6956959/?reload=true)
- [On-demand VM provisioning for cloudlet-based cyber-foraging in resource-constrained environments](http://ieeexplore.ieee.org/abstract/document/7026285/)
- [Cyber-foraging for improving survivability of mobile systems](http://ieeexplore.ieee.org/abstract/document/7357644/)
- [Establishing Trusted Identities in Disconnected Edge Environments](http://ieeexplore.ieee.org/abstract/document/7774673/)

**Closed as completed** 2017-08-08 17:17 UTC
Labels: bug, question
